#
# cmd: kubectl apply -f frontend-app.yml
# https://github.com/tanngoc93/efk-frontend
#
---
apiVersion: v1
kind: ConfigMap # cfg env variables to Pods
metadata:
  name: frontend-cfg
data:
  API_HOST: "api-backend-domain"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: tanngoc93/efk-frontend:latest
        # command: yourCMD
        envFrom:
        - configMapRef:
            name: frontend-cfg # select ConfigMap's name frontend-cfg
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute # https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-ingressroute
metadata:
  name: frontend-ingress
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`domain.com`)
    kind: Rule
    services:
    - name: frontend-service
      port: 80
  tls:
    certResolver: certResolverName # refer traefik/custom-values.yml
